# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

 


 #enverioment variables
env = QT_QPA_PLATFORMTHEME, qt6ct


 #cursor config
env = HYPRCURSOR_THEME, rose-pine-hyprcursor




 #startup apps
exec-once = hyprpaper
exec-once = ~/bin/random-wallpaper.sh
exec-once = waybar
exec-once = discord 
exec-once = hypridle
exec-once = fcitx5


 #defaults
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$browser = opera-gx
$calc = rofi -show calc -modi calc

 
 #keybinds
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, A, exec, pavucontrol
bind = $mainMod, W, exec, $browser
bind = $mainMod, F, fullscreen, 0
bind = ALT, SPACE, exec, $calc
bind = CTRL ALT, Delete, exec, ~/bin/power-menu



 #move window to direction
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d


 #change active windows
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d


 #move to and between workspaces
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9 


 #move and resize floating windows
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


input {
    kb_layout = fi
}


 #monitor setup
monitor = HDMI-A-1, 1920x1080@180, 0x0, 1
monitor = DVI-D-1, 1920x1080@60, 1920x0, 1
