hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("~bin/random-wallpaper.sh")
	hl.exec_cmd("discord")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("fcitx5")
end)
